name: Python CICD for delivery
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8 test
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
    
    - name: Checkout Own Repo to cloud
      uses: actions/checkout@v2.4.0
      with: 
        repository: jamz903/SimpCity
    
    - name: Linter Check with Flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics 
        
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
    - name: Set environment variables for version number
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
    - name: Echo Version Tag
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}    
    - name: Create Download Directory
      run: mkdir downloads

    - name: Create docs
      run: |
        python -m pydoc -w ./
        mv *.html ./downloads
        
    - name: upload documents
      uses: actions/upload-artifact@v2
      with:
        name: assetDocuments
        path: downloads      
        
    - name: Download Content
      uses: actions/download-artifact@v2
      with:
        name: assetDocuments  
        
    - name: Create GitHub release
      id: create-new-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE_VERSION }}
        release_name: Release ${{ env.RELEASE_VERSION }}    
        
    - name: Archive site content
      uses: thedoctor0/zip-release@master
      with:
        filename: content.zip
        
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-new-release.outputs.upload_url }}
        asset_path: ./content.zip
        asset_name: ${{ env.RELEASE_VERSION }}.zip
        asset_content_type: application/zip
   
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        # Required mail server address:
        server_address: smtp.gmail.com
        # Required mail server port:
        server_port: 465
        # Required mail subject:
        subject: SimpCity Release ${{ env.RELEASE_VERSION }}
        # Required recipients' addresses:
        to: jamietohhl@gmail.com
        # Required sender full name (address can be skipped):
        from: Jamie Toh
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # Optional plain body:
        body: |
          There has been a new release created under ${{github.repository}}! 
          View our Release: https://github.com/${{ github.repository }}/releases/tag/${{ env.RELEASE_VERSION }}
        # Optional carbon copy recipients:
        cc: justin80@live.com.sg
        # Optional recipient of the email response:
        reply_to: jamietohhl@gmail.com
        # Optional unsigned/invalid certificates allowance:
        ignore_cert: true
        # Optional converting Markdown to HTML (set content_type to text/html too):
        convert_markdown: true
        # Optional priority: 'high', 'normal' (default) or 'low'
        priority: normal
